version: '3.1'
name: api-thebarber-production

services:
  mongodb:
    image: mongo
    restart: on-failure:5 # On error, try to restart for a maximum of 5 times
    ports:
      - 27031:27017
    environment:
      MONGO_INITDB_DATABASE: api
    volumes:
      - dbvolumethebarberproduction:/data/db

  api:
    build:
      context: .
      dockerfile: ./../packages/api/Dockerfile
    env_file:
      - ./../packages/api/.env.production.local
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/my-google-secret
    ports:
      - 3001:3001 # External:What Is Set In Main.ts
    secrets:
      - my-google-secret 


  front:
    build:
      context: ../.
      dockerfile: packages/front/Dockerfile
    ports:
      - 8081:80


volumes:
  dbvolumethebarberproduction:

secrets:
  my-google-secret:
    file: C:\Users\kelvi\school\sem5\thebarber-f8bd6-firebase-adminsdk-zoil2-0fe452e824.json